name: release

on:
  push:
    branches:
      - master

jobs:
  build-release:
    runs-on: windows-latest

    env:
      FiveMSolutionPath: saltychat\SaltyChat-FiveM.sln
      HUDSolutionPath: saltyhud\SaltyHUD-FiveM.sln
      TalkieSolutionPath: saltytalkie\SaltyTalkie-FiveM.sln

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages (FiveM)
        run: nuget restore $env:FiveMSolutionPath

      - name: Restore NuGet packages (HUD)
        run: nuget restore $env:HUDSolutionPath

      - name: Restore NuGet packages (Talkie)
        run: nuget restore $env:TalkieSolutionPath
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Prepare release
        run: .\Build-Release.ps1
        shell: powershell

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "release/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
